
version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    image: digitalocean.com/php
    container_name: ${APP_NAME}.app
    restart: unless-stopped
    tty: true
    volumes:
       - ./src:/var/www
       - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  # Web server
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}.nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}.db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - dbdata:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_USER: davis
      MYSQL_PASSWORD: Derived49!
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Derived49!}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

# Volume definitions
volumes: 
  dbdata:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge